<?php

global $f_currencies, $f_currency_signs;

$f_currencies = array(
	"AUD" => "Australian Dollar",
	"CAD" => "Canadian Dollar",
	"CNY" => "Chinese Yaun",
	"CZK" => "Czech Koruna",
	"DKK" => "Danish Krone",
	"EUR" => "Euro",
	"HKD" => "Hong Kong Dollar",
	"HUF" => "Hungarian Forint",
	"INR" => "Indian Rupee",
	"ILS" => "Israeli New Sheqel",
	"JPY" => "Japanese Yen",
	"MXN" => "Mexican Peso",
	"NGN" => "Nigerian Naira",
	"NOK" => "Norwegian Krone",
	"NZD" => "New Zealand Dollar",
	"PHP" => "Philippine Peso",
	"PLN" => "Polish Zloty",
	"GBP" => "Pound Sterling",
	"RUB" => "Russian Ruble",
	"SGD" => "Singapore Dollar",
	"SEK" => "Swedish Krona",
	"CHF" => "Swiss Franc",
	"TWD" => "Taiwan New Dollar",
	"THB" => "Thai Baht",
	"USD" => "U.S. Dollar",
);

$f_currency_signs = array(
	"AUD" => "$",
	"CAD" => "$",
	"CNY" => "¥",
	"CZK" => "Kč",
	"DKK" => "kr",
	"EUR" => "€",
	"HKD" => "$",
	"HUF" => "Ft",
	"INR" => "₹",
	"ILS" => "₪",
	"JPY" => "¥",
	"MXN" => "$",
	"NGN" => "₦",
	"NOK" => "kr",
	"NZD" => "$",
	"PHP" => "₱",
	"PLN" => "zł",
	"GBP" => "£",
	"RUB" => "₽",
	"SGD" => "$",
	"SEK" => "kr",
	"CHF" => "Fr.",
	"TWD" => "$",
	"THB" => "฿",
	"USD" => "$",
);