<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.2 INSTALLER - Monday 23rd of December 2013 01:28:48 AM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "", 

		"providers" => array ( 
			// openid providers
			"OpenID" => array (
				"enabled" => false
			),

			"AOL"  => array ( 
				"enabled" => false 
			),

			"Yahoo" => array ( 
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"Google" => array ( 
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "579974435417346", "secret" => "63ec224287cf2a26caf72ae72a7f35ec" )
			),

			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "pgh96PRi2aWyM0wPa3vc7g", "secret" => "wzT4UJ5FXe5N7CyB8VcFkjnnJKAGkxvK0fL4HNPJO0E" ) 
			),

			// windows live
			"Live" => array ( 
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),

			"MySpace" => array ( 
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"LinkedIn" => array ( 
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),
			
			"Tumblr" =>   array ( 
					   "enabled"   => true,
					   "keys"   => array ( "key" => "GVbIHC6NFS58h60Jkv5ZpgSGXcFF9aOSZSnQq3fiKxPyUk826I", "secret" => "vyknsHJT5xQzgVk6ZvANmaTHJDYJvKPwRBmZZHp4MSTggODyel" )
			),
			
			"Foursquare" => array (
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
